config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users, only: [:new, :create]
  resources :products do
  	resource :vote, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  url         :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Product < ApplicationRecord
  belongs_to :user
  has_many :votes

  validates :name, presence: true
  validates :url, presence: true

  def voted_by?(user)
  	votes.exists?(user: user)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(100)
#  password_digest :string
#  name            :string(100)
#  twitter_handle  :string(50)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
	has_many :products
	has_many :votes

	
	has_secure_password validations: false
	validates :email, uniqueness: true, format: /@/
	validates :password, presence: true, on: :create
	validates :password, length: {in: 6..20}, allow_nil: true
	validates :name, presence: true
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  product_id :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Vote < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def sign_in(user)
  	cookies.permanent.signed[:user_id] = user.id
  	@current_user = user
  end

  def sign_out
  	cookies.delete(:user_id)
  	@current_user = nil
  end

  private
    def signed_in?
    	!current_user.nil?
    end
    helper_method :signed_in?

    def current_user
  		  @current_user ||= User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
      rescue ActiveRecord::RecordNotFound
    end	
    helper_method :current_user

  def private_access
    redirect_to :login unless signed_in?    
  end  

  def public_access
    redirect_to root_path if signed_in?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :private_access, except: [:index, :show]

  def index
  	@products = Product.all
  end

  def new
  	@product = Product.new
  end

  def create	
  	@product = Product.new(product_params)
    @product.user = current_user
  	if @product.save
  		redirect_to products_path, notice: "Product has been created"
  	else
  		@errors = @product.errors.full_messages
  		render :new
  	end		
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path, notice: "Product has been Edited"
    else
      @errors = @errors.errors.full_messages
      render :edit
    end    
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: "Product has been deleted"
  end



  private
  def product_params
  	params.require(:product).permit(:name, :url, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :private_access, only: [:destroy]
  before_action :public_access, except: [:destroy]

  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
  		sign_in(user)
  		redirect_to root_path
  	else
  		render :new
  	end	
  end

  def destroy
  	sign_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render:new  
    end
	end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :twitter_handle)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def create
    product = Product.find(params[:product_id])
    product.votes.create(user: current_user)

    redirect_to root_path
  end

  def destroy
    product = Product.find(params[:product_id])
    product.votes.where(user: current_user).take.try(:destroy)

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def form_title	
		@product.new_record? ? "Create Product" : "Edit Product"
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductHunt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<% if flash[:notice] %>
		<div class="alert alert-info"><%= flash[:notice] %></div>
	<% end %>
  <nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Product Hunt", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>
              <li><%= link_to "Salir", logout_path, method: :delete %></li>
              <li><%= link_to "<span class='glyphicon glyphicon-plus'></span>".html_safe, new_product_path %></li>
            <% else %>
              <li><%= link_to "Regístrate", new_user_path %></li>
              <li><%= link_to "Login", login_path %></li>
            <% end %>
          </ul>
          <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
          </form>
        </div><!-- /.navbar-collapse -->
      </div>
    </div>
  </div><!-- /.container -->
</nav>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container">
	<div class="row">
	  <div class="col-sm-6 col-sm-offset-3">
	   <h1><%= form_title %></h1>

	   	<% if @product.errors.any? %>
		    <div class="alert alert-danger">
          <ul>
            <% @product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
	   	<% end %>
	     <%= form_for @product do |f|  %>
	   		<div class="form-group">
	   			<%= f.text_field :name, class: "form-control input-lg", placeholder: "Enter name of product"  %>
	   		</div>
	   		<div class="form-group">
	   			<%= f.url_field :url, class: "form-control input-lg", placeholder: "Enter product url"  %>
	   		</div>
	   		<div class="form-group">
	   			<%= f.text_area :description, class: "form-control input-lg", placeholder: "Enter Product Description"  %>
	   		</div>
	   		<div class="form-group">
	   			<%= f.submit @product.new_record? ? "Create Product" : "Edit product", class: "btn btn-primary btn-lg btn-block"  %>
	   		</div>
	   	  <% end %>
	  </div>
	</div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>
<%if @errors %>
	<% @errors.each do |error| %>
		<%= error %>
	<% end %>
<% end %>		

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      
      <div class="products">
        <%  @products.each do |product| %>
          <div class="product clearfix">
            <% if product.voted_by? current_user %>
              <%= link_to product_vote_path(product), method: :delete, class: "product-upvote upvote-active" do %>
                <span class="upvote-arrow"></span>
                <span class="upvote-count"><%= product.votes.count %></span>
              <% end %>
            <% else %>
              <%= link_to product_vote_path(product), method: :post, class: "product-upvote" do %>
                <span class="upvote-arrow"></span>
                <span class="upvote-count"><%= product.votes.count %></span>
              <% end %>
            <% end %>
            <div class="product-details">
              <span class="product-title"><%= link_to product.name, product %></span>
              <span class="product-description"><%= product.description  %></span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<div class="product-page">
  <header class="product-header">
    <h1><%= @product.name %></h1>
    <p><%= @product.description %></p>
    <a href="<%= @product.url %>" class="btn btn-primary btn-lg" target="_blank">¡Go to!</a>
    <% if signed_in? && @product.user == current_user %> 
    <div class="actions">
      <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_product_path(@product) %>
      <%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, @product, method: :delete, data: { confirm: "Are you sure to delete product?" } %>
    </div>
    <% end %>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div class="votes">
          <h2>Votes</h2>

          <% @product.votes.each do |vote| %>
            <%= vote.user.email %>
          <% end %>
        </div>

        <div class="comments">
          <h2>Coments</h2>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1>Create Account</h1>
			
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      
			<%= form_for @user do |f|%>
			<div class="form-group">
				<%= f.email_field :email, class: "form-control input-lg", placeholder: "Email"%>
			</div>

			<div class="form-group">
				<%= f.password_field :password, class: "form-control input-lg", placeholder: "Password" %>
			</div>

			<div class="form-group">
				<%= f.text_field :name, class: "form-control input-lg", placeholder: "Name" %>
			</div>

			<div class="input-group input-group-lg">
				<span class="input-group-addon" id="basic-addon1">@</span>
				<%= f.text_field :twitter_handle, class: "form-control input-lg", placeholder: "Twitter"%>
			</div>

			<div class="actions">
				<%= f.submit class: "btn btn-primary btn-block btn-lg" %>
			</div>
			<% end %>
		</div>
	</div>
</div>